# services:
#   - type: web
#     name: onco-aristo-bot
#     env: python
#     buildCommand: pip install -r requirements.txt
#     startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false --server.headless=true
#     envVars:
#       - key: GOOGLE_API_KEY
#         sync: false
